name: 'prove-test'

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: git-for-windows/setup-git-for-windows-sdk@v1
        with:
          flavor: minimal
      - shell: bash
        run: |
          set -x
          type prove
          echo $PATH
          prove --version
