name: Auto-publish tags

on:
  push:
    branches:
      - auto-release-on-tag
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Import public GPG keys to verify the tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { execSync } = require('child_process')

            for (const { key_id, raw_key } of (await github.users.listGpgKeysForUser({
                username: 'dscho'
            })).data) {
              execSync(`gpg ${raw_key ? '--import' : `--recv-keys ${key_id}`}`,
                { input: raw_key, stdio: [null, 'inherit', 'inherit'] })
            }
      - name: Check prerequisites
        id: prerequisites
        run: |
          die () {
            echo "$*" >&2
            exit 1
          }

          ref=refs/tags/v0.0.999 # "${{ github.ref }}"
          tag_name=${ref#refs/tags/}
          test "x$ref" != "x$tag_name" || die "Not a tag: $ref"

          train="$(echo "$tag_name" | sed -n 's|^\(v[0-9][0-9]*\)[.0-9]*$|\1|p')"
          test -n "$train" || die "Unexpected tag name: $tag_name"
          echo "$train" >train

          # ONLY FOR DEBUGGING
          train_ref_spec=refs/heads/$train:refs/remotes/origin/$train
          test "$train.0.0" != "$tag_name" || train_ref_spec=
          git fetch --tags https://github.com/git-for-windows/setup-git-for-windows-sdk \
            refs/heads/main:refs/remotes/origin/main $train_ref_spec

          if train_rev="$(git rev-parse --verify "refs/remotes/origin/$train")"
          then
            test 0 -eq "$(git rev-list --count "$ref..$train_rev")" ||
            die "Branch '$train' does not fast-forward to tag '$tag_name'"
          else
            test "$train.0.0" = "$tag_name" || die "Branch '$train' does not yet exist?!?"
          fi

          git tag --verify "$tag_name" || die "Tag does not have a valid signature: $tag_name"

          rev_eq () {
            test "$(git rev-parse "$1")" = "$(git rev-parse "$2")"
          }

          test "$(git rev-parse --verify refs/remotes/origin/main 2>&1)" = \
            "$(git rev-parse --verify "$ref^0")" ||
          die "The tag '$tag_name' does not point to the tip of 'main'"

          echo "$tag_name" >tag_name
          git cat-file tag "$ref" | sed -e '1,/^$/d' -e '/-----BEGIN PGP SIGNATURE-----/,$d' >body

          printf '\nwith\nlines\n' >>body
      - name: Create Release
        if: github.repository_owner == 'git-for-windows'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { readFileSync } = require('fs')

            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: readFileSync('tag_name').toString(),
              draft: true,
              prerelease: false,
              body: readFileSync('body').toString()
            })
      - name: Push to release train branch
        if: github.repository_owner == 'dscho'
        run: git push origin "${{ github.ref }}^0:refs/heads/$(cat train)"
