name: 'test'
on:
  push:
    branches:
      - test

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [minimal, makepkg-git, build-installers, full]
        architecture: [x86_64, i686]
        exclude:
          - flavor: minimal
            architecture: i686
          - flavor: makepkg-git
            architecture: i686
    steps:
      - name: Set up ${{matrix.flavor}} ${{matrix.architecture}}
        uses: dscho/setup-git-for-windows-sdk@test
        with:
          flavor: ${{matrix.flavor}}
          architecture: ${{matrix.architecture}}
      - name: Verify that the Bash of Git for Windows' SDK is used
        shell: bash
        run: |
          set -x
          echo $PATH
          cat /etc/profile
          pwd
          uname -s
          ls -l /mingw64/bin/gcc.exe
          type gcc.exe
          which gcc.exe
          env
          echo "This is the MSYS2 pseudo root: $(cygpath -aw /)"
          curl \
            -LH "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/git-for-windows/git/tarball/HEAD |
          tar -xzf - --strip-components=1
          make -j8